export const events = [
  {
    id: 'evt1',
    name: 'Tech Conference 2025',
    banner: '',
    description: 'Evento anual com foco em inovação tecnológica.',
    created_at: '2025-06-01T10:00:00Z',
    updated_at: '2025-07-01T15:30:00Z',
    startAt: '2025-08-10T09:00:00Z',
    endAt: '2025-08-10T18:00:00Z',
    location: 'Centro de Convenções SP',
    maxParticipants: 500,
    organizer: {
      id: 'usr1',
      email: 'ana.tech@example.com',
      name: 'Ana Souza',
      phone: '11983274625',
    },
    category: {
      title: 'Tecnologia',
    },
  },
  {
    id: 'evt2',
    name: 'Feira de Artesanato',
    startAt: '2025-09-15T10:00:00Z',
    endAt: '2025-09-15T20:00:00Z',
    location: 'Praça Central',
    maxParticipants: 200,
    organizer: {
      id: 'usr2',
      email: 'joao.artesao@example.com',
      name: 'João Artesão',
      phone: '11994728163',
    },
    category: {
      title: 'Cultura',
    },
  },
  {
    id: 'evt3',
    name: 'Hackathon Universitário',
    description: 'Desafio de programação para estudantes universitários.',
    startAt: '2025-10-05T08:00:00Z',
    endAt: '2025-10-06T18:00:00Z',
    location: 'Universidade Federal',
    maxParticipants: 100,
    organizer: {
      id: 'usr3',
      email: 'marcos.dev@example.com',
      name: 'Marcos Lima',
      phone: '11992358741',
    },
    category: {
      title: 'Tecnologia',
    },
  },
  {
    id: 'evt4',
    name: 'Festival de Música',
    startAt: '2025-11-20T16:00:00Z',
    endAt: '2025-11-22T23:00:00Z',
    location: 'Parque das Nações',
    maxParticipants: 1000,
    organizer: {
      id: 'usr4',
      email: 'clara.music@example.com',
      name: 'Clara Mendes',
      phone: '11996471239',
    },
    category: {
      title: 'Entretenimento',
    },
  },
  {
    id: 'evt5',
    name: 'Workshop de Fotografia',
    description: 'Aprenda técnicas de fotografia com profissionais.',
    startAt: '2025-07-25T14:00:00Z',
    endAt: '2025-07-25T18:00:00Z',
    location: 'Espaço Criativo',
    maxParticipants: 50,
    organizer: {
      id: 'usr5',
      email: 'luis.foto@example.com',
      name: 'Luis Oliveira',
      phone: '11993847126',
    },
    category: {
      title: 'Educação',
    },
  },
];

export const categorias = [
  { title: 'Tecnologia' },
  { title: 'Inovação' },
  { title: 'Programação' },
  { title: 'Design' },
  { title: 'Marketing' },
  { title: 'Negócios' },
  { title: 'Entretenimento' },
  { title: 'Empreendedorismo' },
  { title: 'Startups' },
  { title: 'Networking' },
  { title: 'Educação' },
  { title: 'Cursos' },
  { title: 'Workshops' },
  { title: 'Palestras' },
  { title: 'Conferências' },
  { title: 'Feiras' },
  { title: 'Exposições' },
  { title: 'Arte' },
  { title: 'Cultura' },
  { title: 'Artesanato' },
  { title: 'Cinema' },
  { title: 'Teatro' },
  { title: 'Shows' },
  { title: 'Concertos' },
  { title: 'Música' },
  { title: 'Literatura' },
  { title: 'Lançamentos de livros' },
  { title: 'Dança' },
  { title: 'Moda' },
  { title: 'Beleza' },
  { title: 'Saúde' },
  { title: 'Bem-estar' },
  { title: 'Yoga' },
  { title: 'Meditação' },
  { title: 'Esportes' },
  { title: 'Caminhada' },
  { title: 'Corrida' },
  { title: 'Ciclismo' },
  { title: 'Futebol' },
  { title: 'Vôlei' },
  { title: 'Basquete' },
  { title: 'Atividades físicas' },
  { title: 'Jogos' },
  { title: 'Board games' },
  { title: 'eSports' },
  { title: 'Gastronomia' },
  { title: 'Cervejas artesanais' },
  { title: 'Cafés' },
  { title: 'Bebidas' },
  { title: 'Turismo' },
  { title: 'Viagens' },
  { title: 'Ecoturismo' },
  { title: 'Natureza' },
  { title: 'Meio ambiente' },
  { title: 'Sustentabilidade' },
  { title: 'Animais' },
  { title: 'Pets' },
  { title: 'Infantil' },
  { title: 'Juventude' },
  { title: 'Família' },
  { title: 'Comunidade' },
  { title: 'Eventos locais' },
  { title: 'Religião' },
  { title: 'Espiritualidade' },
  { title: 'Voluntariado' },
  { title: 'Causas sociais' },
  { title: 'Doações' },
  { title: 'Política' },
  { title: 'Direitos humanos' },
  { title: 'LGBTQIA+' },
  { title: 'Inclusão' },
  { title: 'Mulheres' },
  { title: 'Pessoas com deficiência' },
  { title: 'Pessoas negras' },
  { title: 'População indígena' },
  { title: 'Empregabilidade' },
  { title: 'Feiras de emprego' },
  { title: 'Hackathons' },
  { title: 'Eventos online' },
  { title: 'Lançamentos' },
  { title: 'Aniversários' },
  { title: 'Casamentos' },
  { title: 'Chás de bebê' },
  { title: 'Encontros' },
  { title: 'Festivais' },
  { title: 'Carnaval' },
  { title: 'São João' },
  { title: 'Natal' },
  { title: 'Ano Novo' },
  { title: 'Outros' },
];
