export const data = [
  {
    id: 'evt1',
    name: 'Tech Conference 2025',
    banner: 'https://example.com/banners/tech2025.jpg',
    description: 'Evento anual com foco em inovação tecnológica.',
    created_at: '2025-06-01T10:00:00Z',
    updated_at: '2025-07-01T15:30:00Z',
    startAt: '2025-08-10T09:00:00Z',
    endAt: '2025-08-10T18:00:00Z',
    location: 'Centro de Convenções SP',
    maxParticipants: 500,
    categoryId: 'cat1',
    organizerId: 'usr1',
    participants: 320,
    organizer: {
      id: 'usr1',
      email: 'ana.tech@example.com',
      password: 'hashed_password',
      role: 'admin',
      name: 'Ana Souza',
      profilePic: 'https://example.com/profiles/ana.jpg',
    },
    category: {
      id: 'cat1',
      title: 'Tecnologia',
    },
  },
  {
    id: 'evt2',
    name: 'Feira de Artesanato',
    startAt: '2025-09-15T10:00:00Z',
    endAt: '2025-09-15T20:00:00Z',
    location: 'Praça Central',
    maxParticipants: 200,
    categoryId: 'cat2',
    organizerId: 'usr2',
    participants: 150,
    organizer: {
      id: 'usr2',
      email: 'joao.artesao@example.com',
      password: 'hashed_password',
      role: 'user',
      name: 'João Artesão',
      profilePic: 'https://example.com/profiles/joao.jpg',
    },
    category: {
      id: 'cat2',
      title: 'Cultura',
    },
  },
  {
    id: 'evt3',
    name: 'Hackathon Universitário',
    description: 'Desafio de programação para estudantes universitários.',
    startAt: '2025-10-05T08:00:00Z',
    endAt: '2025-10-06T18:00:00Z',
    location: 'Universidade Federal',
    maxParticipants: 100,
    categoryId: 'cat1',
    organizerId: 'usr3',
    participants: 90,
    organizer: {
      id: 'usr3',
      email: 'marcos.dev@example.com',
      password: 'hashed_password',
      role: 'admin',
      name: 'Marcos Lima',
      profilePic: 'https://example.com/profiles/marcos.jpg',
    },
    category: {
      id: 'cat1',
      title: 'Tecnologia',
    },
  },
  {
    id: 'evt4',
    name: 'Festival de Música',
    banner: 'https://example.com/banners/musicfest.jpg',
    startAt: '2025-11-20T16:00:00Z',
    endAt: '2025-11-22T23:00:00Z',
    location: 'Parque das Nações',
    maxParticipants: 1000,
    categoryId: 'cat3',
    organizerId: 'usr4',
    participants: 870,
    organizer: {
      id: 'usr4',
      email: 'clara.music@example.com',
      password: 'hashed_password',
      role: 'user',
      name: 'Clara Mendes',
      profilePic: 'https://example.com/profiles/clara.jpg',
    },
    category: {
      id: 'cat3',
      title: 'Entretenimento',
    },
  },
  {
    id: 'evt5',
    name: 'Workshop de Fotografia',
    description: 'Aprenda técnicas de fotografia com profissionais.',
    startAt: '2025-07-25T14:00:00Z',
    endAt: '2025-07-25T18:00:00Z',
    location: 'Espaço Criativo',
    maxParticipants: 50,
    categoryId: 'cat4',
    organizerId: 'usr5',
    participants: 45,
    organizer: {
      id: 'usr5',
      email: 'luis.foto@example.com',
      password: 'hashed_password',
      role: 'user',
      name: 'Luis Oliveira',
      profilePic: 'https://example.com/profiles/luis.jpg',
    },
    category: {
      id: 'cat4',
      title: 'Educação',
    },
  },
];
